// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://govmifmdkudsfhzaarnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvdm1pZm1ka3Vkc2ZoemFhcm51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDE3NDgsImV4cCI6MjA2MDE3Nzc0OH0.7FfN7KHEskLnEGAnffsrIxxQK82okIkkIFVFTjmCRzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);